### ISSUE TITLE
Use twig blocks for form rendering

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#703]
We should replace all `<form>` elements in the twig templates with the twig function `form_start` and `form_end`. We should also move the `action` and `method` (POST, GET) attribute to the PHP files.

This would decouples the business logic from the layout.
## Todo

The following files contains form elements.
- [x] https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/base_layout.html.twig
- [ ] https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/BlockAdmin/edit.html.twig
- [ ] https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/SiteAdmin/create_snapshots.html.twig
- [x] https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/SnapshotAdmin/create.html.twig

**Comment by core23** [comment]
Depends on https://github.com/sonata-project/SonataAdminBundle/issues/4050, because we need to add something to the `Datagrid`.

**Comment by eerison** [comment]
Hey @core23  I saw that [Resources/views/base_layout.html.twig](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/base_layout.html.twig) was already checked as solved, But do you know which PR was it done 👀
